---
- name: install tomcat server
  hosts: all
  become: true

  tasks:
  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre-headless

  - name: extract tomcat packages
    unarchive:
      src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.17/bin/apache-tomcat-10.0.17.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: start tomcat services
    shell: nohup /usr/local/apache-tomcat-10.0.17/bin/startup.sh